title:              ReinaSuo's Space
email:              suowenjiao@gmail.com
description:        A place to write
author:             ReinaSuo
baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://blackrockdigital.github.io"

# Social Profiles
twitter_username:   ReinaSuo
github_username:    ReinaSuo
facebook_username:  ReinaSuo
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
